############ mybatis-plus 配置
mybatis-plus:
  mapper-location:classpath*: /mapper/**Mapper.xml
  # 扫描实体类，多个package之间用 , 隔开
  type-aliases-package: com.example.springbootmybatis.entity

  # 全局的一些配置
  global-config:
    # 0:数据库ID自增  1：自己设置ID  2：全局唯一ID  3：全局唯一ID（UUID）
    id-type: 0
    # 驼峰下划线转换
    db-column-underline: true
    # #刷新mapper
    refresh-mapper: true

  configuration:
    map-underscore-to-camel-case: true
    # 配置缓存的全局开关
    cache-enabled: true
    # 延迟加载开关
    lazy-loading-enabled: true
    # 开启对象延迟加载
    multiple-result-sets-enabled: true


################# Spring 配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pos
    data-username: root
    data-password: 123

